name: Update API Data

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 */2 * * *" # Cron time.

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scheduled:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install requirements
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

      - name: Run Update
        run: python src/eq-scraper.py

      - name: Commit files
        run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add -A
              git commit -m "api-data updated." -a
              git push
      

